language: node_js
node_js:
- '10'
deploy:
  provider: heroku
  api_key:
    secure: F/H6zyrukqXKDKLVyMUXModrRUYN1775Vlr59wQfhJKXnrhPxc2y/c/5kEANgo8wALBvZLGjKSwZP8CTchwQaBtUuAr1ohfH8lP/fz35UninhHZqhnxlGMK9m2ncv+CKU588uAuyTxjeelspJGzvPqzkafKJXT90kJ1/wyxa4odvALIDUS2VsK3klLlhh3DBbvHCVN8MCMtU117WqvAte2AelDzUELaSVmZPbFOHpoYyR3E1XJYS0W0iAIIpqsRZkuOw9bT8zuFKmnh/IukA9PD+ACEdOS/2dGpYU3Q/3YarS+SiH601i3IqwsIzsVbgV+8VBPLPq6guDF0jMOA+7u2qOsjZ/Wy6yCq2+JamdoQXC/GXG9UWeWiczg5LfR8z06HpBEXOcUGIj3uyobTucfIXTLPUqPnNpnvjulvIBMoEvjgYzY3G2aAM7YCWJO31OkLi1PgmWHd1deN9lECsrhJZ6UJ54bQrJd0m7KJQWOk44ibFHqDXlyDzOrFXWNM3ZJTnZ+PZXaZdfIDHVjE7nRKVn9Roo+U8/OBDNoI0taiu+Z17q43I2YsRht/xJv17g4dTxDTBH7+yf/3FDL14hjMtj6TvM7pfZop26ncrUw2x2gpqx/41wTXywLAiZ6VmAap8evWvVNTzGOcP9Q1vjiB68FLg5AN4o4ivvCwrhOg=
